ApplicationId: App Id Here
TenantDomain: tenant.onmicrosoft.com
CertificateThumbprint: Client Certificate Thumbprint
NotifyExpireInDays: [15, 10, 7, 5, 3, 1]
NotifyUsers: true
SenderAddress: noreply_password_expiration@domain.tld
RedirectAllNotifications: true
RedirectTo:
  - debug@domain.tld
SendSummaryToAdmins: false
AdminRecipients:
  - admin_recipient1@domain.tld
  - admin_recipient2@domain.tld
Subject: "ATTENTION: Your Office 365 Password Will Expire $expireInDays"
Attachments: []
EmailTemplate: .\resource\user_notification_template.html
SaveHTMLEmailToFolder: ""
